/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bd.Data;
import bd.DatosConexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.sql.SQLException;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import modelo.DB;
import modelo.MyTreeCellRenderer;
import modelo.Root;
import modelo.TMSelect;
import modelo.Tabla;
import org.fife.ui.rtextarea.*;
import org.fife.ui.rsyntaxtextarea.*;

/**
 *
 * @author Alvaro
 */
public class Aplicacion extends javax.swing.JFrame {

    private DatosConexion datos;
    private Data d;
    private List<String> listaBD;
    private List<Object> listaBDObj;
    private static final long serialVersionUID = 1L;
    public RSyntaxTextArea txtSentencia;
    private final JFileChooser fc = new JFileChooser();

    /*Iconos*/
    private ImageIcon rootIcon = new ImageIcon(getClass().getResource("/imagenes/icon_mysql.png"));
    private ImageIcon BDIcon = new ImageIcon(getClass().getResource("/imagenes/icon_database.png"));
    private ImageIcon TablaIcon = new ImageIcon(getClass().getResource("/imagenes/icon_table.png"));

    public Aplicacion() {
        initComponents();

        /*Prueba de iconos*/
        /*Mouse*/
        this.setVisible(false);
        montarInterfaz();
        txtSentencia = new RSyntaxTextArea(20, 60);
        txtSentencia.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_SQL);
        txtSentencia.setCodeFoldingEnabled(true);
        RTextScrollPane sp = new RTextScrollPane(txtSentencia);
        panelSyntax.add(sp);

        txtSentencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSentenciaKeyReleased(evt);
                contarCaracteres(evt);
            }
        });

        jInicioSesion.setLocationRelativeTo(null);
        jPortada.setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabla = new javax.swing.JFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabSelectop = new javax.swing.JTable();
        btnInsertarFila = new javax.swing.JButton();
        btnAceptarInsertar = new javax.swing.JButton();
        btnCancelarInsertar = new javax.swing.JButton();
        jPortada = new javax.swing.JFrame();
        btnMySQL = new javax.swing.JButton();
        btnSQLServer = new javax.swing.JButton();
        jInicioSesion = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtServer = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeBD = new javax.swing.JTree();
        btnIniciarSeleccionScript = new javax.swing.JButton();
        btnIniciarScriptCompleto = new javax.swing.JButton();
        btnUsarBD = new javax.swing.JButton();
        btnRehacer = new javax.swing.JButton();
        btnDeshacer = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        cboBD = new javax.swing.JComboBox();
        lblContarCaracteres = new javax.swing.JLabel();
        panelSyntax = new javax.swing.JPanel();
        panelCompleto = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        panelTabla = new javax.swing.JScrollPane();
        tabSelect = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        imNuevo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        imAbrir = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        imGuardar = new javax.swing.JMenuItem();
        imGuardarComo = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        imSalir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        imRehacer = new javax.swing.JMenuItem();
        imDeshacer = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        imCortar = new javax.swing.JMenuItem();
        imCopiar = new javax.swing.JMenuItem();
        imPegar = new javax.swing.JMenuItem();
        imBorrar = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        imSeleccionarTodo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        imGeneradorInsert = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jTabla.setIconImage(getIconImage());
        jTabla.setMinimumSize(new java.awt.Dimension(451, 230));

        tabSelectop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabSelectop);

        btnInsertarFila.setText("Insertar");
        btnInsertarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarFilaActionPerformed(evt);
            }
        });

        btnAceptarInsertar.setText("Aceptar");
        btnAceptarInsertar.setEnabled(false);

        btnCancelarInsertar.setText("Cancelar");
        btnCancelarInsertar.setEnabled(false);

        javax.swing.GroupLayout jTablaLayout = new javax.swing.GroupLayout(jTabla.getContentPane());
        jTabla.getContentPane().setLayout(jTablaLayout);
        jTablaLayout.setHorizontalGroup(
            jTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addGroup(jTablaLayout.createSequentialGroup()
                        .addComponent(btnInsertarFila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptarInsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarInsertar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jTablaLayout.setVerticalGroup(
            jTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarFila)
                    .addComponent(btnAceptarInsertar)
                    .addComponent(btnCancelarInsertar))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPortada.setIconImage(getIconImage());
        jPortada.setMinimumSize(new java.awt.Dimension(502, 373));

        btnMySQL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MySQL.png.png"))); // NOI18N
        btnMySQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMySQLActionPerformed(evt);
            }
        });

        btnSQLServer.setText("SQLSERVER");

        javax.swing.GroupLayout jPortadaLayout = new javax.swing.GroupLayout(jPortada.getContentPane());
        jPortada.getContentPane().setLayout(jPortadaLayout);
        jPortadaLayout.setHorizontalGroup(
            jPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPortadaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnMySQL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btnSQLServer, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPortadaLayout.setVerticalGroup(
            jPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPortadaLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSQLServer, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMySQL))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jInicioSesion.setIconImage(getIconImage());
        jInicioSesion.setMinimumSize(new java.awt.Dimension(347, 214));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Iniciar sesión"));
        jPanel1.setMinimumSize(new java.awt.Dimension(327, 182));

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        txtUsuario.setText("root");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel3.setText("Server:");

        txtServer.setText("localhost");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(51, 51, 51)
                        .addComponent(txtServer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInicioSesionLayout = new javax.swing.GroupLayout(jInicioSesion.getContentPane());
        jInicioSesion.getContentPane().setLayout(jInicioSesionLayout);
        jInicioSesionLayout.setHorizontalGroup(
            jInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInicioSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInicioSesionLayout.setVerticalGroup(
            jInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInicioSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        treeBD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                treeBDMouseReleased(evt);
            }
        });
        treeBD.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treeBDValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(treeBD);

        btnIniciarSeleccionScript.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/runSeleccionUP.png"))); // NOI18N
        btnIniciarSeleccionScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSeleccionScriptActionPerformed(evt);
            }
        });

        btnIniciarScriptCompleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/runAllUP.png"))); // NOI18N
        btnIniciarScriptCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarScriptCompletoActionPerformed(evt);
            }
        });

        btnUsarBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usarBDup.png"))); // NOI18N
        btnUsarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsarBDActionPerformed(evt);
            }
        });

        btnRehacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rehacer16.png"))); // NOI18N

        btnDeshacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/deshacer16.png"))); // NOI18N

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminarBDUP.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        cboBD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboBDActionPerformed(evt);
            }
        });

        lblContarCaracteres.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblContarCaracteres.setText("0");

        panelSyntax.setLayout(new java.awt.BorderLayout());

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane3.setViewportView(txtResultado);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
        );

        panelCompleto.addTab("salida", jPanel2);

        tabSelect.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        panelTabla.setViewportView(tabSelect);

        panelCompleto.addTab("select", panelTabla);

        jMenu1.setText("Archivo");

        imNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevoArchivo.png"))); // NOI18N
        imNuevo.setText("Nuevo");
        jMenu1.add(imNuevo);
        jMenu1.add(jSeparator1);

        imAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abrirArchivo.png"))); // NOI18N
        imAbrir.setText("Abrir...");
        imAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(imAbrir);
        jMenu1.add(jSeparator2);

        imGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardarArchivo.png"))); // NOI18N
        imGuardar.setText("Guardar");
        jMenu1.add(imGuardar);

        imGuardarComo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardarArchivo.png"))); // NOI18N
        imGuardarComo.setText("Guardar como...");
        jMenu1.add(imGuardarComo);
        jMenu1.add(jSeparator3);

        imSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        imSalir.setText("Salir");
        jMenu1.add(imSalir);

        menuBar.add(jMenu1);

        jMenu3.setText("Editar");

        imRehacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rehacer.png"))); // NOI18N
        imRehacer.setText("Rehacer");
        jMenu3.add(imRehacer);

        imDeshacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/deshacer.png"))); // NOI18N
        imDeshacer.setText("Deshacer");
        jMenu3.add(imDeshacer);
        jMenu3.add(jSeparator4);

        imCortar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cortar.png"))); // NOI18N
        imCortar.setText("Cortar");
        jMenu3.add(imCortar);

        imCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/copiar.png"))); // NOI18N
        imCopiar.setText("Copiar");
        jMenu3.add(imCopiar);

        imPegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pegar.png"))); // NOI18N
        imPegar.setText("Pegar");
        jMenu3.add(imPegar);

        imBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        imBorrar.setText("Borrar");
        jMenu3.add(imBorrar);
        jMenu3.add(jSeparator5);

        imSeleccionarTodo.setText("Seleccionar Todo");
        jMenu3.add(imSeleccionarTodo);

        menuBar.add(jMenu3);

        jMenu2.setText("Herramientas");

        imGeneradorInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/predefinedIcon.png"))); // NOI18N
        imGeneradorInsert.setText("Generador Insert");
        imGeneradorInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imGeneradorInsertActionPerformed(evt);
            }
        });
        jMenu2.add(imGeneradorInsert);

        menuBar.add(jMenu2);

        jMenu4.setText("Ejecutar");
        menuBar.add(jMenu4);

        jMenu5.setText("Ayuda");
        menuBar.add(jMenu5);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSyntax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboBD, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUsarBD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIniciarScriptCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIniciarSeleccionScript, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeshacer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRehacer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblContarCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCompleto))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRehacer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeshacer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIniciarSeleccionScript, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIniciarScriptCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUsarBD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboBD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelSyntax, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblContarCaracteres)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSeleccionScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSeleccionScriptActionPerformed
        revisarCadena();
        cargarArbol();
        cargarComboBDDespues();
    }//GEN-LAST:event_btnIniciarSeleccionScriptActionPerformed

    private void btnUsarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsarBDActionPerformed
        seleccionarBD();
    }//GEN-LAST:event_btnUsarBDActionPerformed

    private void btnIniciarScriptCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarScriptCompletoActionPerformed
        scriptCompleto();
        cargarArbol();
        cargarComboBDDespues();
    }//GEN-LAST:event_btnIniciarScriptCompletoActionPerformed

    private void treeBDValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeBDValueChanged
        activacionBtnSeleccionarBD();

    }//GEN-LAST:event_treeBDValueChanged

    private void cboBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboBDActionPerformed
        seleccionarBDPorCombo();
    }//GEN-LAST:event_cboBDActionPerformed

    private void btnMySQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMySQLActionPerformed
        jInicioSesion.setVisible(true);
    }//GEN-LAST:event_btnMySQLActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            String pass = "";
            for (char c : txtClave.getPassword()) {
                pass = pass + c;
            }
            datos = new DatosConexion(txtServer.getText(), "mysql", txtUsuario.getText(), pass);
            d = new Data(datos);
            cargarMySQL();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarBD();
        reiniciarArbolYCombo();
        cargarArbol();
        cargarComboBDDespues();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void treeBDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeBDMouseReleased
        if (evt.getClickCount() == 2) {
            TreePath[] paths = treeBD.getSelectionPaths();
            for (TreePath path : paths) {
                try {
                    d = new Data(datos);
                    System.out.println(path.getLastPathComponent());
                    String cadena = path.getLastPathComponent().toString();
                    cadena = "SELECT * FROM " + cadena;
                    List<String[]> listaSelect = d.selectBD(cadena);
                    String[] nombreColumna = listaSelect.get(0);
                    listaSelect.remove(0);
                    TMSelect modelo = new TMSelect(listaSelect, datos, nombreColumna);
                    tabSelect.setModel(modelo);
                    panelCompleto.setSelectedIndex(1);
                    //jTabla.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Aplicacion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_treeBDMouseReleased

    private void imGeneradorInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imGeneradorInsertActionPerformed
        String[] args = null;
        Aplication.main(args);
    }//GEN-LAST:event_imGeneradorInsertActionPerformed

    private void imAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imAbrirActionPerformed
        abrirArchivo(evt);
    }//GEN-LAST:event_imAbrirActionPerformed

    private void btnInsertarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarFilaActionPerformed

    }//GEN-LAST:event_btnInsertarFilaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Aplicacion().setVisible(false);
                }
            });
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Aplicacion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Aplicacion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Aplicacion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Aplicacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarInsertar;
    private javax.swing.JButton btnCancelarInsertar;
    private javax.swing.JButton btnDeshacer;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIniciarScriptCompleto;
    private javax.swing.JButton btnIniciarSeleccionScript;
    private javax.swing.JButton btnInsertarFila;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMySQL;
    private javax.swing.JButton btnRehacer;
    private javax.swing.JButton btnSQLServer;
    private javax.swing.JButton btnUsarBD;
    private javax.swing.JComboBox cboBD;
    private javax.swing.JMenuItem imAbrir;
    private javax.swing.JMenuItem imBorrar;
    private javax.swing.JMenuItem imCopiar;
    private javax.swing.JMenuItem imCortar;
    private javax.swing.JMenuItem imDeshacer;
    private javax.swing.JMenuItem imGeneradorInsert;
    private javax.swing.JMenuItem imGuardar;
    private javax.swing.JMenuItem imGuardarComo;
    private javax.swing.JMenuItem imNuevo;
    private javax.swing.JMenuItem imPegar;
    private javax.swing.JMenuItem imRehacer;
    private javax.swing.JMenuItem imSalir;
    private javax.swing.JMenuItem imSeleccionarTodo;
    private javax.swing.JButton jButton8;
    private javax.swing.JFrame jInicioSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFrame jPortada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JFrame jTabla;
    private javax.swing.JLabel lblContarCaracteres;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTabbedPane panelCompleto;
    private javax.swing.JPanel panelSyntax;
    private javax.swing.JScrollPane panelTabla;
    private javax.swing.JTable tabSelect;
    private javax.swing.JTable tabSelectop;
    private javax.swing.JTree treeBD;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextField txtServer;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void cargarArbol() {
        try {
            treeBD.setCellRenderer(new MyTreeCellRenderer());

            Root mysql = new Root();
            mysql.setNombre("MySQL");
            mysql.setIcon(rootIcon);

            //DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("MySQL");
            d = new Data(datos);
            listaBD = d.mostrarBD();
            for (String l : listaBD) {
//                DefaultMutableTreeNode bd = new DefaultMutableTreeNode(l);
//                raiz.add(bd);
                DB bd = new DB();
                bd.setNombre(l);
                bd.setIcon(BDIcon);
                List<String> listaTablas = d.showTablas(l);
                //DefaultMutableTreeNode tab = null;
                for (String lis : listaTablas) {
                    //tab = new DefaultMutableTreeNode(lis);
                    //bd.add(tab);
                    Tabla tabla = new Tabla();
                    tabla.setNombre(lis);
                    tabla.setIcon(TablaIcon);
                    bd.addTabla(tabla);
                }
                mysql.addBD(bd);
            }
            /*Raiz*/
            DefaultMutableTreeNode root = new DefaultMutableTreeNode(mysql);
            /*Bds*/
            for (DB bd : mysql.getBds()) {
                DefaultMutableTreeNode bdsNode = new DefaultMutableTreeNode(bd);
                /*Tablas*/
                for (Tabla t : bd.getTablas()) {
                    DefaultMutableTreeNode tablaNode = new DefaultMutableTreeNode(t);
                    bdsNode.add(tablaNode);
                }
                root.add(bdsNode);
            }
            DefaultTreeModel modelo = new DefaultTreeModel(root);
            treeBD.setModel(modelo);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

    }

    private void cargarComboBD() {
        try {
            cboBD.removeAllItems();

            d = new Data(datos);
            listaBDObj = d.mostrarBDObj();
            for (Object l : listaBDObj) {
                cboBD.addItem(l);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Aplicacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private String consultaSeleccionada() {
        /*Método para utilizar solo el texto seleccionado del JTextArea*/
        String consulta = txtSentencia.getSelectedText();
        System.out.println(consulta);
        return consulta;
    }

    private void seleccionarBD() {
        try {
            d = new Data(datos);
            DefaultMutableTreeNode BDSeleccionada = (DefaultMutableTreeNode) treeBD.getLastSelectedPathComponent();
            String seleccion = BDSeleccionada.getUserObject().toString();

            cboBD.getModel().setSelectedItem(seleccion);
            datos.setBd(seleccion);
            //d.seleccionarBDLista(seleccion);
        } catch (SQLException ex) {
            Logger.getLogger(Aplicacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void revisarCadena() {
        try {
            String cadena = consultaSeleccionada();
            String[] consulta = cadena.split("\\s+");
            d = new Data(datos);
            if (consulta[0].equalsIgnoreCase("create") /*&& consulta[1].equalsIgnoreCase("table")*/) {
                d.crearTabla(cadena);
                txtResultado.setText("Operación realizada .");
            } else if (consulta[0].equalsIgnoreCase("select")) {
                List<String[]> listaSelect = d.selectBD(cadena);
                String[] nombreColumna = listaSelect.get(0);
                listaSelect.remove(0);
                TMSelect modelo = new TMSelect(listaSelect, datos, nombreColumna);
                tabSelect.setModel(modelo);
                panelCompleto.setSelectedIndex(1);
                //jTabla.setVisible(true);
            } else if (consulta[0].equalsIgnoreCase("show") && consulta[1].equalsIgnoreCase("tables;")) {
                String tablas = d.mostrarTablas(cadena);
                txtResultado.setText(tablas);
            } else if (consulta[0].equalsIgnoreCase("insert")) {
                d.insertarDatos(cadena);
                txtResultado.setText("Dato(s) ingresado(s) ok.");
            } else if (consulta[0].equalsIgnoreCase("delete")) {
                d.eliminarDatos(cadena);
                txtResultado.setText("Dato(s) eliminado(s) ok.");
            } else if (consulta[0].equalsIgnoreCase("update")) {
                d.actualizarDatos(cadena);
                txtResultado.setText("Dato(s) actualizado(s) ok.");
            } else if (consulta[0].equalsIgnoreCase("use")) {
                d.usarBDLista(cadena);
                cboBD.getModel().setSelectedItem(consulta[1]);
                txtResultado.setText("BD cambiada..");
            }
        } catch (SQLException ex) {
            txtResultado.setText(ex.getMessage());
        }
    }

    private void activacionBtnIniciarScriptSeleccionado() {
        if (txtSentencia.getText().equals("")) {
            btnIniciarSeleccionScript.setEnabled(false);
        }
    }

    private void activarBtnIniciarScriptSeleccionado() {
        btnIniciarSeleccionScript.setEnabled(true);

        activacionBtnIniciarScriptSeleccionado();
    }

    private void scriptCompleto() {
        /*Método para ejecutar el JTextArea Completo*/
        try {
            String cadena = txtSentencia.getText();
            String[] consulta = cadena.split("\\s+");
            d = new Data(datos);
            if (consulta[0].equalsIgnoreCase("create") /*&& consulta[1].equalsIgnoreCase("table")*/) {
                d.crearTabla(cadena);
                txtResultado.setText("Tabla creada.");
            } else if (consulta[0].equalsIgnoreCase("select")) {
                List<String[]> listaSelect = d.selectBD(cadena);
                String[] nombreColumna = listaSelect.get(0);
                listaSelect.remove(0);
                TMSelect modelo = new TMSelect(listaSelect, datos, nombreColumna);
                tabSelect.setModel(modelo);
                panelCompleto.setSelectedIndex(1);
                //jTabla.setVisible(true);
            } else if (consulta[0].equalsIgnoreCase("show") && consulta[1].equalsIgnoreCase("tables;")) {
                String tablas = d.mostrarTablas(cadena);
                txtResultado.setText(tablas);
            } else if (consulta[0].equalsIgnoreCase("insert")) {
                d.insertarDatos(cadena);
                txtResultado.setText("Dato(s) ingresado(s) ok.");
            } else if (consulta[0].equalsIgnoreCase("delete")) {
                d.eliminarDatos(cadena);
                txtResultado.setText("Dato(s) eliminado(s) ok.");
            } else if (consulta[0].equalsIgnoreCase("update")) {
                d.actualizarDatos(cadena);
                txtResultado.setText("Dato(s) actualizado(s) ok.");
            }
        } catch (SQLException ex) {
            txtResultado.setText(ex.getMessage());
        }
    }

    private void activacionBtnSeleccionarBD() {
        DefaultMutableTreeNode BDSeleccionada = (DefaultMutableTreeNode) treeBD.getLastSelectedPathComponent();
        try {
            if (!BDSeleccionada.isRoot()) {
                btnUsarBD.setEnabled(true);
            } else {
                btnUsarBD.setEnabled(false);
            }
        } catch (NullPointerException ex) {

        }

    }

    private void activarDesactivarBotones() {
        activacionBtnIniciarScriptSeleccionado();
        btnUsarBD.setEnabled(false);
    }

    private void montarInterfaz() {
        this.setVisible(false);
        jPortada.setVisible(true);

        /*Títulos*/
        this.setTitle("SF");
        jInicioSesion.setTitle("Autenticación");
        jTabla.setTitle("Visualización Tabla");
        jPortada.setTitle("Selección");

        toolTipBotones();
    }

    private void cargarMySQL() {
        this.setVisible(true);
        jInicioSesion.setVisible(false);
        jPortada.setVisible(false);
        cargarArbol();
        cargarComboBD();
        activarDesactivarBotones();
    }

    private void eliminarBD() {
        ImageIcon icon = new ImageIcon(getClass().getResource("../imagenes/confirmacion.png"));
        try {
            String BDSeleccionada = cboBD.getModel().getSelectedItem().toString();

            int opcion = JOptionPane.showConfirmDialog(this, "Desea Eliminar La BD [" + BDSeleccionada + "]", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
            /*si = 0, no = 1*/
            if (opcion == 0) {
                d.eliminarBD(BDSeleccionada);
            } else {
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }

    private void reiniciarArbolYCombo() {
        cboBD.setSelectedIndex(0);
        treeBD.setSelectionRow(0);
    }

    private void cargarComboBDDespues() {
        try {
            String BDSeleccionada = cboBD.getSelectedItem().toString();
            cboBD.removeAllItems();

            d = new Data(datos);
            listaBDObj = d.mostrarBDObj();
            for (Object l : listaBDObj) {
                cboBD.addItem(l);
            }
            cboBD.getModel().setSelectedItem(BDSeleccionada);
        } catch (SQLException ex) {
            Logger.getLogger(Aplicacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void contarCaracteres(java.awt.event.KeyEvent evt) {
//        System.out.println(txtSentencia.getText().length());
        lblContarCaracteres.setText(Integer.toString(txtSentencia.getText().length()));
    }

    private void seleccionarBDPorCombo() {
        try {
            String BDSeleccionada = cboBD.getModel().getSelectedItem().toString();

            datos.setBd(BDSeleccionada);
        } catch (NullPointerException ex) {
            System.out.println(ex.getMessage());
        }
    }

    private void txtSentenciaKeyReleased(java.awt.event.KeyEvent evt) {
        activarBtnIniciarScriptSeleccionado();
    }

    private void abrirArchivo(ActionEvent evt) {
        if (evt.getSource() == imAbrir) {
            int returnVal = fc.showOpenDialog(this.panelSyntax);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();

                Scanner s = null;
                try {
                    s = new Scanner(new BufferedReader(new FileReader(file)));

                    String abrir = "";
                    while (s.hasNextLine()) {
                        abrir = abrir + s.nextLine() + "\n";
                    }
                    txtSentencia.setText(abrir);
                } catch (FileNotFoundException ex) {
                } finally {
                    if (s != null) {
                        s.close();
                    }
                }
            } else {
            }
        }
    }

    private void toolTipBotones() {
        btnUsarBD.setToolTipText("Seleccionar Base De Datos");
        btnEliminar.setToolTipText("Eliminr Base De Datos Seleccionada");
        btnIniciarScriptCompleto.setToolTipText("Ejecutar Código");
        btnIniciarSeleccionScript.setToolTipText("Ejecutar Fracción De Código");
        cboBD.setToolTipText("Base De Datos");
        btnMySQL.setToolTipText("MySQL");
        btnSQLServer.setToolTipText("SQLServer");
        btnDeshacer.setToolTipText("Deshacer");
        btnRehacer.setToolTipText("Rehacer");
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/iconoPrincipal.png"));

        return retValue;
    }
}